name: Tests
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                es_version:
                    - { image: 'elasticsearch:6.8.13', lib: '^6.0' }
                    - { image: 'elasticsearch:7.10.1', lib: '^7.0' }
                    - { image: 'opensearchproject/opensearch:1.2.4', lib: '^7.0'}

                php_version:
                    - '7.4'
                    - '8.0'
                    # Currently disabled as proxy-manager for php8.1 is not released yet.
                    # - '8.1'

        name: PHP ${{ matrix.php_version }} against ${{ matrix.es_version.image }}
        services:
            elasticsearch:
                image: ${{ matrix.es_version.image }}
                ports:
                    - '9200:9200'
                options: >-
                    --env discovery.type=single-node

        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP with pecl extension
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  extensions: :opcache

            - name: Adding correct version of elastica to composer.json
              run: composer require --no-update ruflin/elastica ${{ matrix.es_version.lib }}
            - run: composer install

            - name: Waiting for ES server to become available
              run: ./wait-for-it.sh localhost:9200

            - run: vendor/bin/phpunit --coverage-clover coverage.xml
              env:
                  ES_ENDPOINT: 'http://localhost:9200/'
                  XDEBUG_MODE: coverage
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  file: ./coverage.xml
